Repository TeamHous/Hous-Android, pull requests merged in 2022-07, with the labels that each got.

#7 #6 [ui] 바텀네비 / 바텀네비 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/hous_aos/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/res/color/sel_bot_navi_home_color.xml
  app/src/main/res/color/sel_bot_navi_profile_color.xml
  app/src/main/res/color/sel_bot_navi_rule_color.xml
  app/src/main/res/drawable/ic_bookmark_fill.xml
  app/src/main/res/drawable/ic_bookmark_stroke.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_home_stroke.xml
  app/src/main/res/drawable/ic_person_fill.xml
  app/src/main/res/drawable/ic_person_stroke.xml
  app/src/main/res/drawable/sel_bot_navi_home.xml
  app/src/main/res/drawable/sel_bot_navi_profile.xml
  app/src/main/res/drawable/sel_bot_navi_rule.xml
  app/src/main/res/drawable/shape_bot_navi_home.xml
  app/src/main/res/drawable/shape_bot_navi_profile.xml
  app/src/main/res/drawable/shape_bot_navi_rule.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bot_navi.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐉원용🐉, ui, pull request🔥

#10 #9 [ui] main / 툴바 구현
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, ui, pull request🔥

#13 #11 [feat] main / 프래그먼트 전환 구현
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_rules.xml
Labels: 🐼영주🐼, ui, pull request🔥, feat

#14 #12 [feat] 오각형 뷰 구현
  app/src/main/java/com/hous/hous_aos/ui/pentagon/Pentagon.kt
Labels: 🐉원용🐉, pull request🔥, feat

#17 #16 [fix] shape 네이밍 수정
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/res/drawable/shape_blue_fill_20_ract.xml
  app/src/main/res/drawable/shape_red_fill_20_ract.xml
  app/src/main/res/drawable/shape_yellow_fill_20_ract.xml
  app/src/main/res/layout/activity_main.xml
Labels: 🐉원용🐉, fix

#21 #20 [chore] 폰트 추가
  app/src/main/res/font/montserrat_bold.ttf
  app/src/main/res/font/montserrat_medium.ttf
  app/src/main/res/font/montserrat_semibold.ttf
Labels: 🐼영주🐼, chore

#27 #18 [ui] 규칙홈/ 상단 리사이클러뷰 구현
  app/src/main/res/drawable-hdpi/ic_rules_beer.webp
  app/src/main/res/drawable-mdpi/ic_rules_beer.webp
  app/src/main/res/drawable-xhdpi/ic_rules_beer.webp
  app/src/main/res/drawable-xxhdpi/ic_rules_beer.webp
  app/src/main/res/drawable-xxxhdpi/ic_rules_beer.webp
  app/src/main/res/drawable/ic_rules_rule_bg.xml
  app/src/main/res/drawable/ic_rules_smile.xml
  app/src/main/res/drawable/ic_rules_todo_plus.xml
  app/src/main/res/drawable/shape_puple_fill_10_ract.xml
  app/src/main/res/layout/fragment_rules.xml
  app/src/main/res/layout/item_rules_rule.xml
  app/src/main/res/values/colors.xml
Labels: 🐻준원🐻, ui, pull request🔥

#24 #14 [ui] 홈 / coming up 리사이클러뷰 구현
  app/src/main/java/com/hous/hous_aos/ui/home/ComingUpAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/ComingUpData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/res/drawable-hdpi/ic_plus.png
  app/src/main/res/drawable-mdpi/ic_plus.png
  app/src/main/res/drawable-xhdpi/ic_plus.png
  app/src/main/res/drawable-xxhdpi/ic_plus.png
  app/src/main/res/drawable-xxxhdpi/ic_plus.png
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/shape_blue_fill_20_rect.xml
  app/src/main/res/drawable/shape_red_fill_20_rect.xml
  app/src/main/res/drawable/shape_yellow_bg_fill_16_rect.xml
  app/src/main/res/drawable/shape_yellow_fill_20_rect.xml
  app/src/main/res/drawable/shape_yellow_home_fill_16_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_coming_up.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, ui, pull request🔥

#29 #19 [ui] 규칙 추가 뷰 / 규칙 추가 ui 구현
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt
  app/src/main/res/drawable/ic_alarmoff.xml
  app/src/main/res/drawable/ic_alarmon.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_open.xml
  app/src/main/res/drawable/ic_plus_blue.xml
  app/src/main/res/values/strings.xml
Labels: 🐉원용🐉, ui, pull request🔥

#30 #25 [ui] rules 리사이클러뷰 생성
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RulesData.kt
  app/src/main/res/drawable/shape_blue_bg_fill_16_rect.xml
  app/src/main/res/drawable/shape_blue_fill_circle.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_rules.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, ui, pull request🔥

#35 #34 [feat] 기초 네트워크 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/api/ProfileApi.kt
  app/src/main/java/com/hous/hous_aos/data/api/RulesApi.kt
  app/src/main/java/com/hous/hous_aos/data/source/local/LocalDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/local/LocalDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/di/LocalSourceModule.kt
  app/src/main/java/com/hous/hous_aos/di/NetworkModule.kt
  app/src/main/java/com/hous/hous_aos/di/RemoteSourceModule.kt
Labels: 🐉원용🐉, pull request🔥, feat

#41 #33 [ui] profile 리사이클러뷰 생성
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/ProfileAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/ProfileData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/ToDoAdapter.kt
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_profile_blue.xml
  app/src/main/res/drawable/ic_profile_gray.xml
  app/src/main/res/drawable/ic_profile_green.xml
  app/src/main/res/drawable/ic_profile_purple.xml
  app/src/main/res/drawable/ic_profile_red.xml
  app/src/main/res/drawable/ic_profile_yellow.xml
  app/src/main/res/drawable/shape_g2_fill_10_rect.xml
  app/src/main/res/drawable/shape_purple_fill_10_rect.xml
  app/src/main/res/drawable/shape_yellow_bg_fill_10_rect.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_rules.xml
  app/src/main/res/layout/item_home_profile.xml
  app/src/main/res/layout/item_home_profile_copy.xml
  app/src/main/res/layout/item_home_rules.xml
  app/src/main/res/layout/item_home_to_do.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, ui, pull request🔥

#48 #46 [ui] main / 툴바 수정
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ComingUpAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ProfileAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/RulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ToDoAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/res/drawable/ic_main_edit.xml
  app/src/main/res/drawable/ic_main_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, ui, pull request🔥

#54 #45 [ui] 프로필 / 프로필 empty뷰 구현
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileData.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TagAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TagData.kt
  app/src/main/res/drawable/ic_profile_default.xml
  app/src/main/res/drawable/ic_profile_lock.xml
  app/src/main/res/drawable/ic_profile_next.xml
  app/src/main/res/drawable/shape_red_bg2_fill_8_rect.xml
  app/src/main/res/drawable/shape_red_bg2_fill_circle.xml
  app/src/main/res/drawable/shape_red_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_red_fill_15_rect.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_profile_tag.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, pull request🔥, feat

#56 [fix] #53 홈 / 리스트어댑터로 변경
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ComingUpAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/RulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ToDoAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_today_to_do.xml
  app/src/main/res/layout/item_home_coming_up.xml
  app/src/main/res/layout/item_rules_today_to_do_item_one.xml
Labels: 🐼영주🐼, fix

#57 #55 [fix] 홈 / 아이템 변경
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ComingUpAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_coming_up.xml
  app/src/main/res/layout/item_home_profile.xml
  app/src/main/res/layout/item_home_profile_copy.xml
Labels: 🐼영주🐼, pull request🔥, fix

#59 #31 [feat] 규칙 추가 / 규칙 추가 뷰 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/hous_aos/data/model/request/NewRulesRequest.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/NewRulesResponse.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRuleActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CategoryDropDown.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CategoryItem.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CheckBox.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/Day.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/DayList.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/DeleteButton.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerAddButton.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerBox.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerDropDown.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerItem.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleTextField.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleToolBar.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/RuleAddButton.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/State.kt
  app/src/main/res/layout/activity_new_rule.xml
Labels: 🐉원용🐉, pull request🔥, feat

#61 [feat] 규칙 추가 뷰 / 규칙 추가 뷰 기능 구현
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRuleActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CategoryDropDown.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CategoryItem.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CheckBox.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/Day.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/DayList.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/DeleteButton.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerAddButton.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerBox.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerDropDown.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerItem.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleTextField.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleToolBar.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/RuleAddButton.kt
Labels: 🐉원용🐉, pull request🔥, feat

#66 [fate] 성향 테스트 ui / 성향 테스트 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyTestActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TestInfoActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TypeTest.kt
  app/src/main/java/com/hous/hous_aos/util/BindingAdapter.kt
  app/src/main/res/color/sel_type_test_btn_color.xml
  app/src/main/res/drawable-hdpi/ic_test_red.png
  app/src/main/res/drawable-hdpi/illu_test_01.png
  app/src/main/res/drawable-mdpi/ic_test_red.png
  app/src/main/res/drawable-mdpi/illu_test_01.png
  app/src/main/res/drawable-xhdpi/ic_test_red.png
  app/src/main/res/drawable-xhdpi/illu_test_01.png
  app/src/main/res/drawable-xxhdpi/ic_test_red.png
  app/src/main/res/drawable-xxhdpi/illu_test_01.png
  app/src/main/res/drawable-xxxhdpi/ic_test_red.png
  app/src/main/res/drawable-xxxhdpi/illu_test_01.png
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_left.xml
  app/src/main/res/drawable/ic_right.xml
  app/src/main/res/drawable/sel_type_test_btn.xml
  app/src/main/res/drawable/shape_g1_fill_15_rect.xml
  app/src/main/res/drawable/shape_g3_fill_15_rect.xml
  app/src/main/res/drawable/shape_red_bg2_fill_15_rect.xml
  app/src/main/res/drawable/shape_red_fill_10_rect.xml
  app/src/main/res/drawable/shape_white_fill_20_rect.xml
  app/src/main/res/drawable/test_img.xml
  app/src/main/res/layout/activity_tendency_test.xml
  app/src/main/res/layout/activity_test_info.xml
  app/src/main/res/layout/dialog_type_test_stop.xml
  app/src/main/res/layout/item_tendency_test.xml
  app/src/main/res/values/strings.xml
Labels: 🐉원용🐉, pull request🔥, feat

#69 #68 [feat] 룸메이트 카드 성향결과 / 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/hous_aos/ui/profile/ResultData.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ResultViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyResultActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyViewModel.kt
  app/src/main/java/com/hous/hous_aos/util/BindingAdapter.kt
  app/src/main/res/drawable/shape_15_rect.xml
  app/src/main/res/drawable/shape_21_rect.xml
  app/src/main/res/drawable/shape_blue_bg_fill_21_rect.xml
  app/src/main/res/drawable/shape_green_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_purple_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_purple_bg_fill_21_rect.xml
  app/src/main/res/drawable/shape_red_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_red_bg_fill_21_rect.xml
  app/src/main/res/drawable/shape_yellow_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_yellow_bg_fill_21_rect.xml
  app/src/main/res/layout/activity_tendency_result.xml
  app/src/main/res/layout/item_tendency_test.xml
Labels: 🐼영주🐼, pull request🔥, feat

#73 #70 [feat] / wrapper class, room Id 더미 데이터 생성
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/java/com/hous/hous_aos/data/model/WrapperClass.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesDataSourceImpl.kt
Labels: 🐉원용🐉, pull request🔥, feat

#75 #64 [ui/ feat] 규칙카테고리 뷰/규칙 카테고리뷰 UI 구현 및 기능 구현
  app/build.gradle
  app/src/main/java/com/hous/hous_aos/data/entity/rules/RulesTableResponse.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/HomeRulesCategoryAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/IconColor.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/edit_category/EditCategoryFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/my_to_do/MyToDoAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/new_category/NewCategoryFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/rules_table/GeneralRulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/rules_table/KeyRulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/rules_table/RulesTableFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/today_to_do/ItemToDoViewType.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/today_to_do/TodayTodoAdapter.kt
  app/src/main/res/drawable/shape_rules_table_blue_fill_rec.xml
  app/src/main/res/layout/fragment_edit_category.xml
  app/src/main/res/layout/fragment_my_to_do.xml
  app/src/main/res/layout/fragment_rules_table.xml
  app/src/main/res/layout/item_rules_my_to_do.xml
  app/src/main/res/layout/item_rules_table_general.xml
  app/src/main/res/layout/item_rules_table_keys.xml
  app/src/main/res/layout/item_rules_today_to_do_item_multi.xml
  app/src/main/res/layout/item_rules_today_to_do_item_one.xml
Labels: 🐻준원🐻, ui, pull request🔥, feat

#81 #70 [feat] 홈 / 뷰모델 및 기능 추가
  app/src/main/java/com/hous/hous_aos/ui/home/ComingUpData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomieData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/ProfileData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/ToDoData.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ComingUpAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/EventAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/HomieAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ProfileAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/RulesAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/ToDoAdapter.kt
  app/src/main/res/drawable/shape_blue_bg_fill_10_rect.xml
  app/src/main/res/drawable/shape_blue_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_green_bg_fill_10_rect.xml
  app/src/main/res/drawable/shape_purple_bg_fill_10_rect.xml
  app/src/main/res/drawable/shape_purple_bg_fill_15_rect.xml
  app/src/main/res/drawable/shape_red_bg_fill_10_rect.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_coming_up.xml
  app/src/main/res/layout/item_home_event.xml
  app/src/main/res/layout/item_home_homie.xml
  app/src/main/res/layout/item_home_homie_copy.xml
  app/src/main/res/layout/item_home_rules.xml
  app/src/main/res/layout/item_home_to_do.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, pull request🔥, feat

#84 #82 [feat] 프로필 / 뷰모델 설정
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/HomieAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileData.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TagAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TagData.kt
  app/src/main/res/drawable/ic_profile_blue.xml
  app/src/main/res/drawable/ic_profile_green.xml
  app/src/main/res/drawable/ic_profile_purple.xml
  app/src/main/res/drawable/ic_profile_red.xml
  app/src/main/res/drawable/ic_profile_yellow.xml
  app/src/main/res/drawable/ic_s_blue.xml
  app/src/main/res/drawable/ic_s_gray.xml
  app/src/main/res/drawable/ic_s_green.xml
  app/src/main/res/drawable/ic_s_purple.xml
  app/src/main/res/drawable/ic_s_red.xml
  app/src/main/res/drawable/ic_s_yellow.xml
  app/src/main/res/drawable/shape_blue_fill_8_rect.xml
  app/src/main/res/drawable/shape_green_fill_8_rect.xml
  app/src/main/res/drawable/shape_purple_fill_8_rect.xml
  app/src/main/res/drawable/shape_red_fill_8_rect.xml
  app/src/main/res/drawable/shape_yellow_fill_8_rect.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_profile_tag.xml
  gradle.properties
Labels: 🐼영주🐼, pull request🔥, feat

#95 #78 [error]에러 수정
  .idea/sonarlint/issuestore/3/9/39d6c0c76e591eac5ee36e8b973da5f4b4465d61
  .idea/sonarlint/issuestore/3/c/3c0606852dfabb407d6f65ecfd7d0a3ff676a8f9
  .idea/sonarlint/issuestore/6/c/6c30efff69b84fdb046a46f2951cb8a9fd32211d
  .idea/sonarlint/issuestore/7/8/785acd60510d7fdb2333d19e116febe3217fb980
  .idea/sonarlint/issuestore/b/a/bafa83d8ac6d0b17589912f20c744ccdaea49ab4
  .idea/sonarlint/issuestore/c/0/c0dba72a099d08685ed1930b324f08a371400f54
  .idea/sonarlint/issuestore/d/a/daa7a485e989920901983255e1e4378afcc625d3
  .idea/sonarlint/issuestore/f/4/f4a01d6a4fcb971362ec00a83903fd3902f52164
  .idea/sonarlint/issuestore/index.pb
  app/build.gradle
  app/src/main/java/com/hous/hous_aos/ui/home/EventViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesViewModel.kt
Labels: hotfix🚨

#97 [ui] 오각형 뷰 추가/ 오각형 뷰 추가
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/TendencyTestBox.kt
  app/src/main/java/com/hous/hous_aos/ui/pentagon/Pentagon.kt
  app/src/main/java/com/hous/hous_aos/ui/pentagon/PentagonBxo.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐉원용🐉, ui, pull request🔥

#99 #98 [feat] 프로필 홈화면 조회하기 API 연동
  app/src/main/java/com/hous/hous_aos/data/api/ProfileApi.kt
  app/src/main/java/com/hous/hous_aos/data/repository/ProfileRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/di/RepositoryModule.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileViewModel.kt
Labels: 🐉원용🐉, pull request🔥, feat

#104 #96 [feat] 규칙홈/ 오늘의 ToDo 서버 통신
  app/build.gradle
  app/src/main/java/com/hous/hous_aos/data/api/RulesApi.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/RulesTodayInfoListResponse.kt
  app/src/main/java/com/hous/hous_aos/data/repository/RulesTodayRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/RulesTodayRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesTodayDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesTodayDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/di/RemoteSourceModule.kt
  app/src/main/java/com/hous/hous_aos/di/RepositoryModule.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/today_to_do/TodayToDoFragment.kt
  app/src/main/res/layout/fragment_today_to_do.xml
  app/src/main/res/layout/item_rules_today_to_do_item_multi.xml
  app/src/main/res/values/strings.xml
Labels: 🐻준원🐻, feat

#106 #92 홈 / 홈 api 연결
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/HomeResponse.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/di/RepositoryModule.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RoommateCardActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/EventAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/HomieAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
Labels: 🐼영주🐼, pull request🔥, feat

#107 #103 [feat] 성향 테스트 점수 등록 및 수정 API 연동
  app/src/main/java/com/hous/hous_aos/data/api/ProfileApi.kt
  app/src/main/java/com/hous/hous_aos/data/model/request/PutTestResultRequest.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/TypeTestListResponse.kt
  app/src/main/java/com/hous/hous_aos/data/repository/ProfileRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TypeTest.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: 🐉원용🐉, pull request🔥, fix

#116 #112 [feat] 이벤트 조회하기 서버연결
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/EventResponse.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
Labels: 🐉원용🐉, pull request🔥, feat

#119 #115 [feat] 이벤트 삭제 api 연동
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
Labels: 🐉원용🐉, pull request🔥, feat

#122 #120 [chore] 프로필 성향 테스트 뷰 더미 데이터 제거
  app/src/main/java/com/hous/hous_aos/data/entity/TypeTest.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyViewModel.kt
Labels: 🐉원용🐉, pull request🔥, chore

#124 #121 규칙홈/ 오늘의 todo api 붙이기
  .idea/sonarlint/issuestore/6/2/62d41b83de73ea9637f2d82462ade5cacfbbeb3a
  .idea/sonarlint/issuestore/c/0/c0dba72a099d08685ed1930b324f08a371400f54
  .idea/sonarlint/issuestore/f/d/fd4265ceda91e9f809dda5aa92e0a974ea2dc3db
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/com/hous/hous_aos/data/api/RulesApi.kt
  app/src/main/java/com/hous/hous_aos/data/repository/RulesTodayRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/RulesTodayRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesTodayDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteRulesTodayDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesViewModel.kt
  app/src/main/res/layout/fragment_my_to_do.xml
Labels: 🐻준원🐻, pull request🔥, feat

#123 #108 [feat] 홈 / 호미 성향카드 서버 붙이기
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/entity/Homie.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/HomeResponse.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/TestResultResponse.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RommateViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RoommateCardActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/HomieAdapter.kt
  app/src/main/res/layout/activity_roommate_card.xml
Labels: 🐼영주🐼, pull request🔥, feat

#134 #133 [feat] 확장함수 구현
  app/src/main/java/com/hous/hous_aos/data/entity/ColorSet.kt
  app/src/main/java/com/hous/hous_aos/ui/pentagon/PentagonBxo.kt
  app/src/main/java/com/hous/hous_aos/util/GetColorSet.kt
Labels: 🐉원용🐉, feat

#131 #108 성향테스트결과(프로필) / 네트워크 연결
  app/src/main/java/com/hous/hous_aos/data/api/ProfileApi.kt
  app/src/main/java/com/hous/hous_aos/data/entity/ResultData.kt
  app/src/main/java/com/hous/hous_aos/data/model/response/TestResultResponse.kt
  app/src/main/java/com/hous/hous_aos/data/repository/ProfileRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteProfileDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ResultViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyResultActivity.kt
  app/src/main/java/com/hous/hous_aos/util/BindingAdapter.kt
  app/src/main/res/layout/activity_tendency_result.xml
Labels: 🐼영주🐼, pull request🔥, feat

#137 #132 [feat] 성향테스트결과(호미) / 네트워크 연결
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RoommateCardActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ResultViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyResultActivity.kt
  app/src/main/res/layout/activity_tendency_result.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: 🐼영주🐼, pull request🔥, feat

#136 #135 [feat] pentagon 비율 조절
  app/src/main/java/com/hous/hous_aos/ui/pentagon/Pentagon.kt
  app/src/main/java/com/hous/hous_aos/ui/pentagon/PentagonBxo.kt
Labels: 🐉원용🐉, pull request🔥, feat

#128 #125 [ui] 스플래쉬 이미지, 대표 아이콘 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/splash.json
  app/src/main/java/com/hous/hous_aos/ui/splash/IntroActivity.kt
  app/src/main/res/drawable/ic_icon.xml
  app/src/main/res/layout/activity_intro.xml
Labels: 🐉원용🐉, ui, pull request🔥

#130 #129 [feat] 버튼 기능 추가
  app/src/main/java/com/hous/hous_aos/di/NetworkModule.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleToolBar.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/RuleAddButton.kt
Labels: 🐉원용🐉, pull request🔥, feat

#141 #140 [feat] Event api 연결
  .idea/sonarlint/issuestore/0/3/03d4c39e55320ba045082a68584e03881f8b8181
  .idea/sonarlint/issuestore/0/f/0f6672634b815f76cbfee6b0253fba0710960e01
  .idea/sonarlint/issuestore/1/0/10b76ee27b4add8d39dc615f6462c1d8b5f7b6d3
  .idea/sonarlint/issuestore/3/9/39d6c0c76e591eac5ee36e8b973da5f4b4465d61
  .idea/sonarlint/issuestore/5/e/5e504d6523f743654dea0d5c0c0e8ab67c5e617c
  .idea/sonarlint/issuestore/7/8/785acd60510d7fdb2333d19e116febe3217fb980
  .idea/sonarlint/issuestore/b/2/b26721b771070630419f1a8e4bad81ce5ee1095d
  .idea/sonarlint/issuestore/d/0/d0c6a9cd927bc40634d68f3ec553c28180165621
  .idea/sonarlint/issuestore/e/9/e98602bd100b022ec9e3d498a0a0a80214201e5f
  .idea/sonarlint/issuestore/f/a/faa6b94530686894e93d8c0bbe412e01a2699798
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/com/hous/hous_aos/data/api/HomeApi.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepository.kt
  app/src/main/java/com/hous/hous_aos/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSource.kt
  app/src/main/java/com/hous/hous_aos/data/source/remote/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventDialogFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
Labels: 🐻준원🐻, pull request🔥, feat

#143 #138 [feat] 룸메이트 프로필/ 오각형 뷰 추가
  app/src/main/java/com/hous/hous_aos/ui/home/RommateViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RoommateCardActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/res/layout/activity_roommate_card.xml
Labels: 🐉원용🐉, feat

#148 #142 [feat] put 요청 성공
  .idea/sonarlint/issuestore/c/8/c8b852f746f4284b67be58f2274f60a7631cada8
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/com/hous/hous_aos/ui/home/EventDialogFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventIcon.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
Labels: 🐻준원🐻, pull request🔥, feat

#151 #150 [feat] 중복 클릭 효과 제거
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
Labels: 🐉원용🐉, pull request🔥

#149 #142 홈 이벤트/ 이벤트 삭제 및 추가 api 연결
  .idea/sonarlint/issuestore/0/b/0b960a547e6177adbaecd31a17c32189dd9d4785
  .idea/sonarlint/issuestore/5/e/5e504d6523f743654dea0d5c0c0e8ab67c5e617c
  .idea/sonarlint/issuestore/b/1/b11d733c2a0884113604561857cdf35244e56df2
  .idea/sonarlint/issuestore/c/8/c8b852f746f4284b67be58f2274f60a7631cada8
  .idea/sonarlint/issuestore/d/8/d8d5202a580477950d568da6d924cc8c3e4a29d7
  .idea/sonarlint/issuestore/d/a/daa7a485e989920901983255e1e4378afcc625d3
  .idea/sonarlint/issuestore/f/a/fafe78e0901d47db9d0d5da4f97827305336dca1
  .idea/sonarlint/issuestore/index.pb
  app/src/main/java/com/hous/hous_aos/ui/home/EventDialogFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/EventViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/adapter/EventAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/today_to_do/TodayTodoAdapter.kt
  app/src/main/res/layout/fragment_event_dialog.xml
  app/src/main/res/layout/item_rules_today_to_do_item_multi.xml
  app/src/main/res/layout/item_rules_today_to_do_item_none.xml
  app/src/main/res/layout/item_rules_today_to_do_item_one.xml
  app/src/main/res/values/strings.xml
Labels: 🐻준원🐻, pull request🔥, feat

#156 #155 [fix] 롱클릭 비활성화 및 +버튼 클릭 비활성화
  app/src/main/java/com/hous/hous_aos/ui/rules/HomeRulesCategoryAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesFragment.kt
Labels: 🐻준원🐻, pull request🔥, fix

#154 #153 [fix] 추가하기 버튼 바텀 마진 추가
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt
Labels: 🐉원용🐉, fix

#157 #152 [fix] 디자인 디테일 수정
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/home/RoommateCardActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyResultActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_roommate_card.xml
  app/src/main/res/layout/activity_tendency_result.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_rules.xml
  app/src/main/res/layout/item_tendency_test.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/strings.xml
Labels: 🐼영주🐼, ui, fix, feat

#160 #159 [hotfix] add-text-font
  .idea/sonarlint/issuestore/0/b/0b960a547e6177adbaecd31a17c32189dd9d4785
  .idea/sonarlint/issuestore/2/1/21fc7f9b693802c7c00b7a621dcbbf0602d5b82e
  .idea/sonarlint/issuestore/4/7/47d4431864d6380b67b652e42563df5c84084282
  .idea/sonarlint/issuestore/4/8/487c30dd133881b13261b0af8a7bd4bbeaeec06d
  .idea/sonarlint/issuestore/5/1/51623d3e44e35fe823e9531f871a63482ab5613f
  .idea/sonarlint/issuestore/5/5/55649260a196f1ceaab3fe4bfdbe68184c1efff0
  .idea/sonarlint/issuestore/7/2/7270efe715e6a2a0828a0058494ff6340f1f8382
  .idea/sonarlint/issuestore/7/3/73f6b7749f5aecadc6aff9847575da104696758a
  .idea/sonarlint/issuestore/7/8/785acd60510d7fdb2333d19e116febe3217fb980
  .idea/sonarlint/issuestore/9/0/907c2d7efe535a01b8a6b630148f15f22b28ff7b
  .idea/sonarlint/issuestore/a/5/a5b04cf93d3ef02c30209b6b2bf2396791a01213
  .idea/sonarlint/issuestore/a/c/ac03cce2c366184e88fbc24fd92fe47c1e83c276
  .idea/sonarlint/issuestore/b/d/bd2b79c92c9e108abbd265903b8ae0e9de9b6eaf
  .idea/sonarlint/issuestore/d/6/d62eae69c44b23aa9da7216b52eb0692bded7bf8
  .idea/sonarlint/issuestore/d/a/daa7a485e989920901983255e1e4378afcc625d3
  .idea/sonarlint/issuestore/index.pb
  app/src/main/res/layout/fragment_event_dialog.xml
Labels: 🐻준원🐻, pull request🔥, hotfix🚨

#162 #161 [fix] 다크 모드 제한, 화면 회전 막기, 컴포즈 폰트 에러 수정
  app/debug/output-metadata.json
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRuleActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesScreen.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CategoryItem.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/CheckBox.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/Day.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerBox.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/ManagerDropDown.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleTextField.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/NewRuleToolBar.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/component/RuleAddButton.kt
  app/src/main/java/com/hous/hous_aos/ui/pentagon/PentagonBxo.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 🐉원용🐉, fix

#165 #164 [feat] category name, id
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRuleActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/newrules/NewRulesViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/rules_table/RulesTableFragment.kt
Labels: 🐉원용🐉, pull request🔥, feat

#169 #163 [fix] 카테고리 icon 클릭시 해당 카테고리규칙 띄우는 로직 수정
  app/src/main/java/com/hous/hous_aos/ui/rules/HomeRulesCategoryAdapter.kt
  app/src/main/java/com/hous/hous_aos/ui/rules/RulesFragment.kt
Labels: 🐻준원🐻, fix

#167 #166 [ui] 홈 / key rules, to do 엠티뷰 visibility 설정
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
Labels: 🐼영주🐼, ui, pull request🔥

#170 #168 [fix] to do 코루틴 함수 호출 위치 변경
  app/src/main/java/com/hous/hous_aos/ui/home/EventViewModel.kt
  app/src/main/java/com/hous/hous_aos/ui/home/HomeFragment.kt
  app/src/main/java/com/hous/hous_aos/ui/main/MainActivity.kt
  app/src/main/java/com/hous/hous_aos/ui/profile/TendencyResultActivity.kt
Labels: 🐼영주🐼, pull request🔥, feat
